### ISSUE TITLE
Neovim LSP support

### ISSUE THREAD

**Issue by gasacchi** [rescript-lang/vim-rescript#20]
Hi, I currently using neovim nightly build.
can i use this plugin with https://github.com/neovim/nvim-lspconfig ?
Thanks

**Comment by ryyppy** [comment]
Only if the vim LSP client supports node-ipc communication.. we don't have a stdout, nor socket option.

Use the settings as stated in the coc vim config part in the README and let me know how it went!

**Comment by amiralies** [comment]
it just supports stdout AFAIK.
I think we need to support stdout (many language clients communicate via stdout only) and it should be trivial to implement.

**Comment by gasacchi** [comment]
yes, i try to look on lspconfig in the repo it seems only support stdout. well i'm going to use coc for now, btw thank for response :smile:

**Comment by WhyThat** [comment]
Just for your information you can now configure the builtin LSP thanks to https://github.com/rescript-lang/rescript-vscode/pull/88
Steps:
- `git clone  https://github.com/rescript-lang/rescript-vscode`
- `cd rescript-vscode`
- `npm install`
- `npm run compile`
- `cd analysis && make`
- Add this wherever you configure your LSPs
```lua
local lsp = require'lspconfig'
local configs = require'lspconfig/configs'
local rescriptLspPath = '~/repos/rescript-vscode/server/out/server.js'

if not lsp.rescriptlsp then
  configs.rescriptlsp = {
    default_config = {
      cmd = {'node', rescriptLspPath, '--stdio'};
      filetypes = {"rescript"};
      root_dir = lsp.util.root_pattern('bsconfig.json');
      settings = {};
    };
  }
end
lsp.rescriptlsp.setup{
  -- with your configurations
}

```

**Comment by amiralies** [comment]
rescript supported is [added](https://github.com/neovim/nvim-lspconfig/pull/892) to nvim-lspconfig so assuming you have latest lspconfig version setup is trivial
```lua
require'lspconfig'.rescriptls.setup {
  cmd = {
    'node',
    '<path to server.js>',
    '--stdio'
  }
}

```

**Comment by encephalone** [comment]
For the third day I have been trying to integrate **Rescript support on pure LSP** (Not COC!) In neovim. 
But nothing comes out (the LspInfo command confirms the presence of the client, but there is **no support from him**)!
Tried options with **vs-code-lang-server and the official vim-rescript plugin**. My config:

``` 
call plug#begin()
         Plug 'nvim-lua/completion-nvim'
         Plug 'rescript-lang/vim-rescript'
         Plug 'neovim/nvim-lspconfig'
         Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
call plug#end()

set number

" LSP
lua require('lspconfig').pyright.setup{}
lua require('lspconfig').rescriptls.setup{cmd={'node','~/.config/nvim/plugged/vim-rescript/server/out/server.js','--stdio'}}
 
" Completion
 " lua require('lspconfig').pyright.setup{on_attach=require('completion').on_attach}
 " lua require('lspconfig').rescriptls.setup{on_attach=require('completion').on_attach}

set completeopt=menuone,noinsert,noselect
" Avoid showing message extra message when using completion
set shortmess+=c
let g:completion_enable_auto_popup = 1


" Use completion-nvim in every buffer
 autocmd BufEnter * lua require('completion').on_attach()
```

Can anyone help?

**Comment by amiralies** [comment]
@rocinant3 can you try pointing to server with absolute path?
`/home/<username>/.config/......`
instead of 
`~/.config/...`

**Comment by encephalone** [comment]
@amiralies,  **seems works!**, thank you 

![image](https://user-images.githubusercontent.com/42095220/126033286-9fcb39e3-7583-4145-b9da-3243100724ff.png)



**But what about auto-completion?** 
There is an instruction in my config (usually works with all languages)
```lua require('lspconfig').rescriptls.setup{on_attach=require('completion').on_attach}```

But in this case nvim crashed with error:
```
An error was encountered while processing the FileType Autocommand for "rescript":
E5108: Error executing lua Vim:E928: String required
E5108: Error executing lua Vim:E928: String required
```

**Comment by amiralies** [comment]
I'm not sure if its related with rescript's config.
I use `nvim-compe` and it just works.

**Comment by encephalone** [comment]
Solved a problem! Everything is working. Thanks again
![image](https://user-images.githubusercontent.com/42095220/126033860-712b6c28-7c06-4695-9fd9-9e583d6f4337.png)

**Comment by barkanido** [comment]
@rocinant3 can I ask how?

**Comment by amiralies** [comment]
@barkanido It depends on your config. do you have exact same problem as above?

**Comment by barkanido** [comment]
Eventually it was a bug in the lsp client that was fix fixed

**Comment by mununki** [comment]
~~@amiralies I finally made it works thanks! But the go-to definition seems not working. Should I add the pattern in the configuration additionally?~~

~~My current configuration~~
```
nvim_lsp.rescriptls.setup {
  cmd = {
    'node',
    '/Users/woonki/.local/share/nvim/plugged/vim-rescript/server/out/server.js',
    '--stdio'
  }
}
```

Sorry for interrupting you. I missed some basic stuff by mistake. It works perfectly! Thank you for great work!
