### ISSUE TITLE
vim-rescript change current directory even it's not rescript project

### ISSUE THREAD

**Issue by wingyplus** [rescript-lang/vim-rescript#30]
I found this bug when I working on another project (such as Go or Elixir). The current working directory was change caused by vim-rescript. The fzf plugin affected also. 

I guess that it's because of this line https://github.com/rescript-lang/vim-rescript/blob/master/autoload/rescript.vim#L51. Maybe it should not called `lcd` when it cannot detect rescript project.

**Comment by wingyplus** [comment]
Oh, it's seems dup with #23 ?

**Comment by ryyppy** [comment]
are you sure this is actually caused by our plugin? The autocommand for updating the environment only triggers when you create / open a new `.res`, `.resi` file: https://github.com/rescript-lang/vim-rescript/blob/master/ftplugin/rescript.vim#L17

**Comment by amiralies** [comment]
I can confirm this happens for me too. I.e opening a monorepo which contains only scala code.

**Comment by ryyppy** [comment]
@amiralies @wingyplus can you please follow the install instructions of #32 and check if this fixes your issue?

**Comment by amiralies** [comment]
not heavily tested but works as expected for me :+1:

**Comment by Dkendal** [comment]
Can confirm that this happens to me as well, regardless of where I am in the filesystem

**Comment by ryyppy** [comment]
@Dkendal can you try the fix posted above and check if it solves the issue on your machine? If I get some more confirmations that this fix works reliably, I will probably just merge and tag a release

**Comment by Dkendal** [comment]
@ryyppy looks like it works!
