### ISSUE TITLE
Testing for RC 2.1.0

### ISSUE THREAD

**Issue by ryyppy** [rescript-lang/vim-rescript#41]
Hey @amiralies, could you check out the latest master and test if `coc-rename` works for you?
Added the newest LSP impl and want to make sure it works on someone else's machine this time.

Anyone else here, feel free to test as well!

**Comment by amiralies** [comment]
I've tested with both coc and neovim's lsp client. neovim is fine, coc has that problem you shared in another issue. I try to find more info about that.

**Comment by ryyppy** [comment]
should be good now
