### ISSUE TITLE
coc -> Rename doesn't work across files

### ISSUE THREAD

**Issue by ryyppy** [rescript-lang/vim-rescript#42]
There's an issue where a `coc-rename` over multiple files fails with `[coc.nvim] Error on applyEdits: Cannot read property 'uri' of null`

To reproduce, create the following files:

```
// MyFile1.res

let a = 1
```

```
// MyFile2.res

let b = MyFile1.a
```

Then try to `coc-rename` `MyFile1.a` to `MyFile1.something`, and it will first ask to load 1 file from disk, and then fail with the error message mentioned above.

My wild guess is that it's an issue with how coc interprets the rename command result. Either our LSP is not sticking to certain protocol conventions, or coc-vim is at fault. Hard to debug.

**Comment by amiralies** [comment]
It seems it happens because coc doesn't handle `.` (current path) in URIs. I think per standard it's okay to have `.` in uri and it should be fixed in coc rathar than our side (not sure tho).

to confirm this you can do a little hack in server to see if it works or not.
after else block in this [line](https://github.com/rescript-lang/rescript-vscode/blob/master/server/src/server.ts#L297) insert this code to remove `.` from URIs
```ts
    locations = locations.map(x => ({
      ...x,
      uri: x.uri
        .split('/')
        .filter(c => c !== '.')
        .join('/'),
    }));
```

**Comment by ryyppy** [comment]
Yeah that worked... okay, gonna report that one on the coc-vim repo then.

**Comment by ryyppy** [comment]
Okay, just so we know what we are talking about, this is how the paths look like for my specific rename query:

```json
[
    {
        "uri": "file:///Users/ryyppy/Projects/rescript-association/vim-rescript/examples/rescript-project/././src/polySyntax.res",
        "range": {
            "start": {
                "line": 8,
                "character": 28
            },
            "end": {
                "line": 8,
                "character": 32
            }
        }
    },
    {
        "uri": "file:///Users/ryyppy/Projects/rescript-association/vim-rescript/examples/rescript-project/./src/recordExample.res",
        "range": {
            "start": {
                "line": 9,
                "character": 11
            },
            "end": {
                "line": 9,
                "character": 15
            }
        }
    },
    {
        "uri": "file:///Users/ryyppy/Projects/rescript-association/vim-rescript/examples/rescript-project/./src/recordExample.res",
        "range": {
            "start": {
                "line": 1,
                "character": 12
            },
            "end": {
                "line": 1,
                "character": 16
            }
        }
    }
]
```

The first uri looks weird though: `././src/...`.

**Comment by amiralies** [comment]
> Yeah that worked... okay, gonna report that one on the coc-vim repo then.

I've opened an issue https://github.com/neoclide/coc.nvim/issues/3104



> The first uri looks weird though: `././src/...`.

Yeah, worth checking what's happening in analysis binary

**Comment by amiralies** [comment]
This is fixed on coc.nvim's master.

**Comment by ryyppy** [comment]
question is when this will be shipped in a new release.. not sure how to use that master version via `Plug`, and if we should provide some instructions on how to do that for the meantime.

**Comment by amiralies** [comment]
this installs coc from master
```
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
```

I suggest to wait until it get released, they release regulary so it should be shipped soon.

**Comment by amiralies** [comment]
This is released on `release` branch

**Comment by ryyppy** [comment]
okay nice, just tried it. Works like a charm.
