### ISSUE TITLE
Syntax: Add support for string interpolation

### ISSUE THREAD

**Issue by amiralies** [rescript-lang/vim-rescript#43]
I'm not sure about the grammar maybe take a look at `syntax` repo.
do we have `$name` or just `${name}`?

**Comment by ryyppy** [comment]
`$name` should theoretically highlight as well, but I think we'd rather nudge ppl to always use the `${name}` variant, since the former requires you to use the j` prefix.

**Comment by amiralies** [comment]
Added back single var syntax in pr
