### ISSUE TITLE
nvim builtin lsp support?

### ISSUE THREAD

**Issue by kkharji** [rescript-lang/vim-rescript#46]
It would be nice to have support to nvim builtin lsp. Thanks

**Comment by amiralies** [comment]
Check here https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#rescriptls

**Comment by kkharji** [comment]
Thanks  a lot @amiralies

**Comment by amiralies** [comment]
No problem, feel free to open issue if you had problems.
I will try add docs/links to this repo
