### ISSUE TITLE
Vim LSP Support

### ISSUE THREAD

**Issue by wilkinson4** [rescript-lang/vim-rescript#50]
Hello,

It would be helpful if there was some sort of documentation on how to get this to work with native vim-lsp.

**Comment by amiralies** [comment]
Since you stated native lsp ? are talking about noevim?
I don't think if vim itself provides native lsp support.
anyway language server lives in `server` directory and you can use that like this in your lsp client:
```sh
node <path to vim-rescript>/server/out/server.js --stdio
```

**Comment by aspeddro** [comment]
see https://github.com/williamboman/nvim-lsp-installer

**Comment by mununki** [comment]
duplicated? #20
